# Generated by Django 5.1.3 on 2024-11-15 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('website', models.URLField()),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
                ('benefits', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
